# fly.toml app configuration file generated for proyecto-final-spgmeta-2024 on 2024-10-15T01:48:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proyecto-final-spgmeta-2024'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
